;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-word-begin
        evil-force-normal-state
        evil-forward-word-begin
        evil-insert
        evil-normal-state
        paredit-open-round
        ))

(setq mc/cmds-to-run-once
      '(
        ))
