" This must be first, because it changes other options as a side effect.
set nocompatible

set shell=sh

call plug#begin('~/.vim/bundle')

Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'

Plug 'vim-scripts/a.vim'
Plug 'benmills/vimux'
Plug 'drmikehenry/vim-headerguard'

Plug 'chrisbra/vim-zsh'
Plug 'ludovicchabant/vim-gutentags'

" Plug 'rking/ag.vim'
Plug 'octol/vim-cpp-enhanced-highlight'

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'rust-lang/rust.vim', { 'for': 'rust' }

Plug 'junegunn/vim-easy-align'

Plug 'tomtom/tcomment_vim'
Plug 'tomtom/tlib_vim'
Plug 'godlygeek/tabular'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'leafgarland/typescript-vim'
Plug 'Quramy/tsuquyomi'

Plug 'vim-airline/vim-airline' | Plug 'vim-airline/vim-airline-themes'

Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-surround'
" Plug 'tpope/vim-rake'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-markdown'
Plug 'tpope/vim-rails'

Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'slim-template/vim-slim', { 'for': 'slim' }
Plug 'scrooloose/nerdtree', { 'on': 'NERDTree' }

Plug 'krisajenkins/vim-projectlocal'
Plug 'AndrewRadev/switch.vim'
Plug 'eshock/vim-matchit'
Plug 'skwp/vim-rspec'
Plug 'mattn/gist-vim'
Plug 'mattn/webapi-vim'

Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

Plug 'kurko/autocoder.vim'
Plug 'mattn/zencoding-vim'

Plug 'sjl/gundo.vim'
Plug 'othree/html5.vim'

Plug 'rhysd/vim-clang-format'
Plug 'kana/vim-operator-user'

Plug 'mattn/emmet-vim'
Plug 'dag/vim2hs', { 'for': 'haskell' }

Plug 'jimenezrick/vimerl', { 'for': 'erlang' }
Plug 'elixir-lang/vim-elixir', { 'for': 'elixir' }

let g:alchemist#elixir_erlang_src= "~/src/"

Plug 'jiangmiao/auto-pairs'

Plug 'fatih/vim-go', { 'for': 'go' }

Plug 'Shougo/vimproc.vim'
Plug 'scrooloose/syntastic'

" Plug 'ajh17/VimCompletesMe'
" Plug 'Shougo/neocomplete.vim'
Plug 'Valloric/YouCompleteMe'
Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }

Plug 'janko-m/vim-test'

Plug 'vim-perl/vim-perl'
" Plug 'nxadm/syntastic-perl6'

call plug#end()

" TODO - TComment to use // C++ style comments in C files

let g:airline_theme='base16_default'

" Go config
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_fmt_command = "goimports"

let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
" let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go']  }
let g:go_list_type = "quickfix"

" Change the leader to ","
let mapleader=","

let g:VimuxOrientation = "h"
let g:airline_powerline_fonts = 1

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-k>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

let g:UltiSnipsExpandTrigger       = "<tab>"
let g:UltiSnipsJumpForwardTrigger  = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"
let g:UltiSnipsSnippetDirectories  = ["snips"]

function! g:UltiSnips_Complete()
  call UltiSnips#ExpandSnippet()
  if g:ulti_expand_res == 0
    if pumvisible()
      return "\<C-n>"
    else
      call UltiSnips#JumpForwards()
      if g:ulti_jump_forwards_res == 0
        return "\<TAB>"
      endif
    endif
  endif
  return ""
endfunction

au InsertEnter * exec "inoremap <silent> " . g:UltiSnipsExpandTrigger . " <C-R>=g:UltiSnips_Complete()<cr>"

let g:airline_powerline_fonts = 1

let g:python_host_prog = '/usr/bin/python2'
let g:python3_host_prog = '/usr/bin/python3'

set foldlevelstart=200
let g:haskell_conceal       = 0
let g:haskell_quasi         = 1
let g:haskell_interpolation = 0
let g:haskell_regex         = 0
let g:haskell_jmacro        = 0
let g:haskell_shqq          = 0
let g:haskell_sql           = 0
let g:haskell_json          = 0
let g:haskell_xml           = 0

let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'
let g:ycm_extra_conf_globlist = ['*']
let g:ycm_show_diagnostics_ui = 1

nnoremap <leader>jd :YcmCompleter GoTo<CR>
nnoremap <leader>jf :YcmCompleter GoToDefinition<CR>
nnoremap <leader>je :YcmCompleter GoToDeclaration<CR>
nnoremap <leader>gt :YcmCompleter GetType<CR>

" TODO: relative path to home?
let g:ycm_rust_src_path = '/home/darth/projects/rust/src'

" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*
" :set statusline+=%{gutentags#statusline()}

" let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

" TODO: try this again later to see if it works"
" let g:syntastic_perl6lib = [ 'lib', '../lib' ]
" let g:syntastic_perl6_checkers = ['jsonerror']
" let g:syntastic_enable_perl6_jsonerror_checker = 1

" Mapping selecting mappings
nmap <leader><tab> <plug>(fzf-maps-n)
xmap <leader><tab> <plug>(fzf-maps-x)
omap <leader><tab> <plug>(fzf-maps-o)

" Insert mode completion
" imap <c-x><c-k> <plug>(fzf-complete-word)
imap <c-x><c-f> <plug>(fzf-complete-path)
imap <c-x><c-j> <plug>(fzf-complete-file-ag)
" imap <c-x><c-l> <plug>(fzf-complete-line)


xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)

let g:syntastic_haskell_checkers = ['']

let g:syntastic_cpp_compiler = 'clang++'
let g:syntastic_cpp_compiler_options = ' -std=c++1y -stdlib=libc++'

" Enable syntastic syntax checking
let g:syntastic_enable_signs=1
let g:syntastic_cpp_check_header = 0

let g:tsuquyomi_disable_quickfix = 1
let g:tsuquyomi_completion_detail = 1

let g:syntastic_typescript_checkers = ['tsuquyomi']

" let g:syntastic_mode_map = { "mode": "passive", "active_filetypes": ["haskell", "go", "c", "cpp", "idris", "rust", "elixir"] }

xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)

" gist-vim defaults
if has("mac")
  let g:gist_clip_command = 'pbcopy'
elseif has("unix")
  let g:gist_clip_command = 'xclip -selection clipboard'
endif
let g:gist_detect_filetype = 1
let g:gist_open_browser_after_post = 1
let g:gist_post_private = 1

" Turn off jslint errors by default
let g:JSLintHighlightErrorLine = 0

" Allow backgrounding buffers without writing them, and remember marks/undo
" for backgrounded buffers
set hidden

" Remember more commands and search history
set history=1000

set number
set ruler

" TODO - check if this is still necessary in vim
" Set encoding
" set encoding=utf-8

" Whitespace stuff
set nowrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

set list listchars=tab:\ \ ,trail:.

set backupcopy=yes

" Searching
set hlsearch
set incsearch
" Make searches case-sensitive only if they contain upper-case characters
set ignorecase
set smartcase
nnoremap <CR> :nohlsearch<CR>/<BS>

" Make tab completion for files/buffers act like bash
set wildmenu

set laststatus=0

" TODO - how does this differ from "longest,list" only?
" Tab completion
set wildmode=list:longest,list:full
set wildignore+=obj,*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*,node_modules,tmp,project/target,target,tags,CMakeFiles,bower_components,dist,_darcs,vcr,app/assets/images,*.dSYM,*.pyc,_build,deps,rel,*.a,priv/static,*.aux,*.dvi,*.xmpi,*.out,*.lot

" TODO - what is the default behavior?
" Remap the tab key to do autocompletion or indentation depending on the
" context (from http://www.vim.org/tips/tip.php?tip_id=102)
" function! InsertTabWrapper()
"     let col = col('.') - 1
"     if !col || getline('.')[col - 1] !~ '\k'
"         return "\<tab>"
"     else
"         return "\<c-p>"
"     endif
" endfunction
"
" inoremap <tab> <c-r>=InsertTabWrapper()<cr>
" inoremap <s-tab> <c-n>

command! W :w

" Status bar
set laststatus=2
set winwidth=75

" Use modeline overrides
set modeline
set modelines=10

set t_Co=256
set bg=dark

let base16colorspace=256  " Access colors present in 256 colorspace
color base16-default

" Directories for swp files
set backupdir=~/.vim/backup
set directory=~/.vim/backup

" Remember last location in file
aug last_location
  au!
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
aug END

" Save undo history
if has('persistent_undo')
  set undofile
  if !isdirectory(expand('~/.vimundo'))
    silent !mkdir ~/.vimundo > /dev/null 2>&1
  endif
  set undodir=~/.vimundo
endif

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Show (partial) command in the status line
set showcmd

" Remove scrollbars
set guioptions-=L
set guioptions-=r
set guioptions-=T

if has("gui_running")
  " Automatically resize splits when resizing MacVim window
  autocmd VimResized * wincmd =

  set vb
  " color Tomorrow-Night
  set lines=40
  set columns=120
endif

" Highlight current line
set cursorline
" set cursorcolumn

" Buffer resizing with arrow keys
nnoremap <Up> <C-w>5-
nnoremap <Down> <C-w>5+
nnoremap <Left> <C-w>5<
nnoremap <Right> <C-w>5>

nnoremap - :Switch<cr>

" Expand %% to directory path of current buffer
cnoremap %% <C-R>=expand('%:h').'/'<CR>
" nnoremap <leader>e :call VimuxRunCommand("make")<cr>
nnoremap <leader>r :call VimuxRunCommand("make ". expand("%h"))<cr>
nnoremap <leader>c :call VimuxRunCommand("make clean")<cr>

" Inserts the path of the currently edited file into a command
" Command mode: Ctrl+P
" TODO - figure out more clever usage for this
cnoremap <C-P> <C-R>=expand("%:p:h") . "/" <CR>

" Open files with <leader>f
noremap <leader>f  :Files ./<CR>
" Open files, limited to the directory of the current files, with <leader>gf
noremap <leader>F  :FZF %%<CR>
noremap <leader>gf :GFiles ./<CR>
noremap <leader>gd :GFiles?<cr>

" Rails specific keystrokes
noremap <leader>gr :topleft :split config/routes.rb<CR>
noremap <leader>gg :topleft 50 :split Gemfile<CR>

noremap <leader>gv :FZF app/views<cr>
noremap <leader>gc :FZF app/controllers<cr>
noremap <leader>gm :FZF app/models<cr>
noremap <leader>gs :FZF app/services<cr>
noremap <leader>gh :FZF app/helpers<cr>
noremap <leader>gl :FZF lib<cr>
noremap <leader>gk :FZF app/assets/stylesheets<cr>
noremap <leader>gj :FZF app/assets/javascripts<cr>

nnoremap <leader>w :VimuxRunCommand("webpack")<cr>

noremap <leader>a :TestSuite<cr>
" Run this file
noremap <leader>t :TestFile<cr>
" Run only the example under the cursor
noremap <leader>T :TestNearest<cr>

nnoremap <leader>b :Buffers<cr>
nnoremap <leader>B :BTags<cr>

nnoremap <C-a> ^
nnoremap <C-e> $

" For easier navigation between windows
nnoremap <C-j> <C-w><C-j>
nnoremap <C-k> <C-w><C-k>
nnoremap <C-h> <C-w><C-h>
nnoremap <C-l> <C-w><C-l>

" Bubble multiple lines
vnoremap <C-Up> <C-w><C-k>
vnoremap <C-Down> <C-w><C-j>
vnoremap <C-Left> <C-w><C-h>
vnoremap <C-Right> <C-w><C-l>

" fat fingers
noremap <F1> <Esc>

inoremap <C-X><C-@> <C-A>
" Emacs style mappings
inoremap      <C-A> <C-O>^
cnoremap      <C-A> <Home>
cnoremap <C-X><C-A> <C-A>

" If at end of a line of spaces, delete back to the previous line.
" Otherwise, <Left>
inoremap <silent> <C-B> <C-R>=getline('.')=~'^\s*$'&&col('.')>strlen(getline('.'))?"0\<Lt>C-D>\<Lt>Esc>kJs":"\<Lt>Left>"<CR>
cnoremap          <C-B> <Left>

" If at end of line, decrease indent, else <Del>
inoremap <silent> <C-D> <C-R>=col('.')>strlen(getline('.'))?"\<Lt>C-D>":"\<Lt>Del>"<CR>
cnoremap          <C-D> <Del>

" If at end of line, fix indent, else <Right>
inoremap <silent> <C-F> <C-R>=col('.')>strlen(getline('.'))?"\<Lt>C-F>":"\<Lt>Right>"<CR>
inoremap          <C-E> <End>
cnoremap          <C-F> <Right>
noremap!          <M-a> <C-O>(
map!              <M-b> <S-Left>
noremap!          <M-d> <C-O>dw
noremap!          <M-e> <C-O>)
map!              <M-f> <S-Right>
noremap!          <M-h> <C-W>
noremap           <M-l> guiww
noremap           <M-u> gUiww
noremap!          <M-l> <Esc>guiw`]a
noremap!          <M-u> <Esc>gUiw`]a
noremap!          <M-{> <C-O>{
noremap!          <M-}> <C-O>}

cnoremap <C-a>  <Home>
cnoremap <C-b>  <Left>
cnoremap <C-f>  <Right>
cnoremap <C-d>  <Delete>
cnoremap <M-b>  <S-Left>
cnoremap <M-f>  <S-Right>
cnoremap <M-d>  <S-right><C-w>
cnoremap <Esc>b <S-Left>
cnoremap <Esc>f <S-Right>
cnoremap <Esc>d <S-right><C-w>
cnoremap <C-g>  <C-c>

" Disable accidental ex mode
nmap Q <NOP>

" Switching between active files in a buffer.
nnoremap <leader><leader> <c-^>

" CTags - TODO - find a good hotkey for this
noremap <leader>lt :!ctags --extra=+f --exclude=public --exclude=node_modules --exclude=.git -R *<CR>
noremap <C-\> :tnext<CR>

noremap <silent> <leader>y :<C-u>silent '<,'>w !pbcopy<CR>

aug various_file_types
  au!
  " Rakefile, Vagrantfile and Gemfile are Ruby
  au BufRead,BufNewFile {Capfile,Gemfile,Rakefile,Vagrantfile,config.ru} set ft=ruby
  au BufRead,BufNewFile *.asm set ft=nasm

  " add json syntax highlighting
  au BufNewFile,BufRead *.json set filetype=javascript

  au BufNewFile,BufRead *.slime set filetype=slim

  au BufNewFile,BufRead *.conf set filetype=conf
  au BufNewFile,BufRead *vimrc set filetype=vim
aug END

" load the plugin and indent settings for the detected filetype
filetype plugin indent on

" % to bounce from do to end etc.
runtime! macros/matchit.vim

" remove unnecessary whitespaces
noremap <leader>ws :%s/ *$//g<cr><c-o><cr>

set pastetoggle=<F5>
set mouse=a

let g:clang_format#code_style = "google"

autocmd FileType h,cc,c,cpp nnoremap <buffer><C-e> :<C-u>ClangFormat<CR>
autocmd FileType h,cc,c,cpp nnoremap <buffer><leader>ha :HeaderguardAdd<CR>
autocmd FileType h,cc,c,cpp vnoremap <buffer><C-e> :ClangFormat<CR>

let g:limelight_paragraph_span = 2
" autocmd BufRead,BufNewFile * Limelight 0.5


nnoremap <Leader>e :call VimuxRunCommand("make")<cr>

" Include user's local vim config
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif

if has("user_commands")
  command! -bang -nargs=? -complete=file E e<bang> <args>
  command! -bang -nargs=? -complete=file W w<bang> <args>
  command! -bang -nargs=? -complete=file Wq wq<bang> <args>
  command! -bang -nargs=? -complete=file WQ wq<bang> <args>
  command! -bang Wa wa<bang>
  command! -bang WA wa<bang>
  command! -bang Q q<bang>
  command! -bang QA qa<bang>
  command! -bang Qa qa<bang>
endif

function! s:profilestop()
  profdel func *
  profdel file *
  qa!
endfunction

function! s:profilestart()
  profile start vim.profile
  profile func *
  profile file *
endfunction

command! -nargs=0 StopProfiling call s:profilestop()

set exrc
set secure
