# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "ehci_pci" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/59fe956b-fdc6-4f55-ae88-f911c726c91c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0807-B08D";
      fsType = "vfat";
    };

  fileSystems."/mnt/arch" =
    { device = "/dev/disk/by-uuid/8e0ce6b0-b472-46af-aada-9e2da2e0455b";
      fsType = "ext4";
    };

  fileSystems."/mnt/gentoo" =
    { device = "/dev/disk/by-uuid/aa284cd7-57da-462a-85a7-d5555260e468";
      fsType = "ext4";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 12;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
