#!/bin/bash

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
else
	alias ls='ls -G'
fi

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias unexecute="find . -iname '*.js' -or -iname '*.html' -or -iname '*.css' -or -iname '*.jpg' -or -iname '*.png' -or -iname '*.gif' -exec chmod -x {} \;"

function lsq() {
  ls -lh $@ | tr -s ' ' | cut -d' ' -f5,8
}

function take {
  mkdir $1
  cd $1
}

# Show most used commands from bash history
function usage {
  history | awk '{a[$2]++}END{for(i in a){print a[i] " " i}}' | sort -rn | head
}

# Usage .. [n]
function .. (){
  local arg=${1:-1};
  local dir=""
  while [ $arg -gt 0 ]; do
    dir="../$dir"
    arg=$(($arg - 1));
  done
  cd $dir #>&/dev/null
}

alias s="apt-cache search"
alias i="sudo apt-get install"
alias r="rails"
alias j="jruby -S "
alias e="redcar"

### Git ###
alias git=hub

function gg() {
  git commit -v -a -m "$*"
}

alias ga="git add"
alias gc="git commit -v"
alias gp="git push"
alias gs="git status"
alias gst="git status"
alias gb="git branch"
alias gba="git branch -a"
alias gl="git pull"
alias gd="git diff"
alias gco="git checkout"
