#!/bin/bash

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

function take {
  mkdir $1
  cd $1
}

function usage {
  history | awk '{a[$2]++}END{for(i in a){print a[i] " " i}}' | sort -rn | head
}

alias s="apt-cache search"
alias i="sudo apt-get install"
alias r="rails"


# Git

function gg() {
  git commit -v -a -m "$*"
}

alias ga="git add"
alias gc="git commit -v"
alias gp="git push"
alias gs="git status"
alias gb="git branch"
alias gco="git checkout"
